# Generated by Django 5.0.3 on 2025-04-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupon', '0002_cupon_delete_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupon',
            old_name='idCupon',
            new_name='idUser',
        ),
    ]
