# Generated by Django 5.0.3 on 2025-04-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupon', '0003_rename_idcupon_cupon_iduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupon',
            old_name='name_Cupon',
            new_name='name',
        ),
    ]
