# Generated by Django 5.0.3 on 2025-05-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupon', '0004_rename_name_cupon_cupon_name'),
        ('producto', '0002_producto_idcategoria_producto_idcupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupon',
            options={'ordering': ['code'], 'verbose_name': 'Cupón', 'verbose_name_plural': 'Cupones'},
        ),
        migrations.RemoveField(
            model_name='cupon',
            name='idUser',
        ),
        migrations.RemoveField(
            model_name='cupon',
            name='name',
        ),
        migrations.AddField(
            model_name='cupon',
            name='code',
            field=models.CharField(db_index=True, default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cupon',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='cupones', to='producto.producto'),
        ),
    ]
