# Generated by Django 5.0.3 on 2025-04-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_categoria_delete_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='idCategoria',
            new_name='idUser',
        ),
    ]
