# Generated by Django 5.0.3 on 2025-04-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_rename_idcategoria_categoria_iduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='name_Categoria',
            new_name='name',
        ),
    ]
