# Generated by Django 5.0.3 on 2025-05-02 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0004_rename_name_categoria_categoria_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='description',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='idUser',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='name',
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Texto descriptivo opcional', null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default=1, help_text='Nombre identificador de la categoría', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
