# Generated by Django 5.0.3 on 2025-04-22 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_rename_idcategoria_categoria_iduser'),
        ('cupon', '0003_rename_idcupon_cupon_iduser'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='idCategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='idCupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cupon.cupon'),
        ),
    ]
