# Generated by Django 5.0.3 on 2025-05-02 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0004_rename_name_categoria_categoria_name'),
        ('producto', '0002_producto_idcategoria_producto_idcupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='description',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idCupon',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idUser',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='price',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='categoria.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
